//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigoBAS_Start.IDMServices.Profiles {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Users.Metadata")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowPublishingWorkMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalizedJobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryDepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivatePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialSecurityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsePrivateMobileForWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ValidToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowPublishingWorkMobile {
            get {
                return this.AllowPublishingWorkMobileField;
            }
            set {
                if ((this.AllowPublishingWorkMobileField.Equals(value) != true)) {
                    this.AllowPublishingWorkMobileField = value;
                    this.RaisePropertyChanged("AllowPublishingWorkMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalizedJobTitle {
            get {
                return this.PersonalizedJobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalizedJobTitleField, value) != true)) {
                    this.PersonalizedJobTitleField = value;
                    this.RaisePropertyChanged("PersonalizedJobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalLocation {
            get {
                return this.PostalLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalLocationField, value) != true)) {
                    this.PostalLocationField = value;
                    this.RaisePropertyChanged("PostalLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryDepartment {
            get {
                return this.PrimaryDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryDepartmentField, value) != true)) {
                    this.PrimaryDepartmentField = value;
                    this.RaisePropertyChanged("PrimaryDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryDepartmentName {
            get {
                return this.PrimaryDepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryDepartmentNameField, value) != true)) {
                    this.PrimaryDepartmentNameField = value;
                    this.RaisePropertyChanged("PrimaryDepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateEmail {
            get {
                return this.PrivateEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateEmailField, value) != true)) {
                    this.PrivateEmailField = value;
                    this.RaisePropertyChanged("PrivateEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateMobile {
            get {
                return this.PrivateMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateMobileField, value) != true)) {
                    this.PrivateMobileField = value;
                    this.RaisePropertyChanged("PrivateMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivatePhone {
            get {
                return this.PrivatePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivatePhoneField, value) != true)) {
                    this.PrivatePhoneField = value;
                    this.RaisePropertyChanged("PrivatePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialSecurityNumber {
            get {
                return this.SocialSecurityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialSecurityNumberField, value) != true)) {
                    this.SocialSecurityNumberField = value;
                    this.RaisePropertyChanged("SocialSecurityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsePrivateMobileForWork {
            get {
                return this.UsePrivateMobileForWorkField;
            }
            set {
                if ((this.UsePrivateMobileForWorkField.Equals(value) != true)) {
                    this.UsePrivateMobileForWorkField = value;
                    this.RaisePropertyChanged("UsePrivateMobileForWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((this.ValidToField.Equals(value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkEmail {
            get {
                return this.WorkEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkEmailField, value) != true)) {
                    this.WorkEmailField = value;
                    this.RaisePropertyChanged("WorkEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkMobile {
            get {
                return this.WorkMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkMobileField, value) != true)) {
                    this.WorkMobileField = value;
                    this.RaisePropertyChanged("WorkMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPhone {
            get {
                return this.WorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneField, value) != true)) {
                    this.WorkPhoneField = value;
                    this.RaisePropertyChanged("WorkPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserRequest", Namespace="http://schemas.datacontract.org/2004/07/Users.Models")]
    [System.SerializableAttribute()]
    public partial class GetUserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DepartmentIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchPhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialSecurityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VigoBAS_Start.IDMServices.Profiles.GetUserRequest.SortDirections SortDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VigoBAS_Start.IDMServices.Profiles.GetUserRequest.SortProperties SortPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VigoBAS_Start.IDMServices.Profiles.GetUserRequest.UserTypes UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DepartmentIds {
            get {
                return this.DepartmentIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIdsField, value) != true)) {
                    this.DepartmentIdsField = value;
                    this.RaisePropertyChanged("DepartmentIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage {
            get {
                return this.ResultsPerPageField;
            }
            set {
                if ((this.ResultsPerPageField.Equals(value) != true)) {
                    this.ResultsPerPageField = value;
                    this.RaisePropertyChanged("ResultsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchPhrase {
            get {
                return this.SearchPhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchPhraseField, value) != true)) {
                    this.SearchPhraseField = value;
                    this.RaisePropertyChanged("SearchPhrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialSecurityNumber {
            get {
                return this.SocialSecurityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialSecurityNumberField, value) != true)) {
                    this.SocialSecurityNumberField = value;
                    this.RaisePropertyChanged("SocialSecurityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VigoBAS_Start.IDMServices.Profiles.GetUserRequest.SortDirections SortDirection {
            get {
                return this.SortDirectionField;
            }
            set {
                if ((this.SortDirectionField.Equals(value) != true)) {
                    this.SortDirectionField = value;
                    this.RaisePropertyChanged("SortDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VigoBAS_Start.IDMServices.Profiles.GetUserRequest.SortProperties SortProperty {
            get {
                return this.SortPropertyField;
            }
            set {
                if ((this.SortPropertyField.Equals(value) != true)) {
                    this.SortPropertyField = value;
                    this.RaisePropertyChanged("SortProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VigoBAS_Start.IDMServices.Profiles.GetUserRequest.UserTypes UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetUserRequest.SortDirections", Namespace="http://schemas.datacontract.org/2004/07/Users.Models")]
        public enum SortDirections : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Asc = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Desc = 1,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetUserRequest.SortProperties", Namespace="http://schemas.datacontract.org/2004/07/Users.Models")]
        public enum SortProperties : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DisplayName = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FirstName = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LastName = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WorkEmail = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GetUserRequest.UserTypes", Namespace="http://schemas.datacontract.org/2004/07/Users.Models")]
        public enum UserTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            All = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Employee = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Temporary = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Student = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserResponse", Namespace="http://schemas.datacontract.org/2004/07/Users.Models")]
    [System.SerializableAttribute()]
    public partial class GetUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VigoBAS_Start.IDMServices.Profiles.Profile[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRowCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VigoBAS_Start.IDMServices.Profiles.Profile[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultsPerPage {
            get {
                return this.ResultsPerPageField;
            }
            set {
                if ((this.ResultsPerPageField.Equals(value) != true)) {
                    this.ResultsPerPageField = value;
                    this.RaisePropertyChanged("ResultsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount {
            get {
                return this.TotalRowCountField;
            }
            set {
                if ((this.TotalRowCountField.Equals(value) != true)) {
                    this.TotalRowCountField = value;
                    this.RaisePropertyChanged("TotalRowCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfilePicture", Namespace="http://schemas.datacontract.org/2004/07/Users.Buddy")]
    [System.SerializableAttribute()]
    public partial class ProfilePicture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VigoBAS_Start.IDMServices.Profiles.Attachment AttachmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VigoBAS_Start.IDMServices.Profiles.Attachment Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://schemas.datacontract.org/2004/07/Users.Buddy")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanUseExternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanUseInternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64Image {
            get {
                return this.Base64ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Base64ImageField, value) != true)) {
                    this.Base64ImageField = value;
                    this.RaisePropertyChanged("Base64Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanUseExternal {
            get {
                return this.CanUseExternalField;
            }
            set {
                if ((this.CanUseExternalField.Equals(value) != true)) {
                    this.CanUseExternalField = value;
                    this.RaisePropertyChanged("CanUseExternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanUseInternal {
            get {
                return this.CanUseInternalField;
            }
            set {
                if ((this.CanUseInternalField.Equals(value) != true)) {
                    this.CanUseInternalField = value;
                    this.RaisePropertyChanged("CanUseInternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgType {
            get {
                return this.ImgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgTypeField, value) != true)) {
                    this.ImgTypeField = value;
                    this.RaisePropertyChanged("ImgType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://basservices.vigobas.no/Users/Profiles", ConfigurationName="IDMServices.Profiles.IProfiles")]
    public interface IProfiles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Get", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetResponse")]
        VigoBAS_Start.IDMServices.Profiles.Profile Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Get", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetAll", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetAllResponse")]
        VigoBAS_Start.IDMServices.Profiles.Profile[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetAll", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetAllResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetForDepartment", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetForDepartmentResponse")]
        VigoBAS_Start.IDMServices.Profiles.Profile[] GetForDepartment(string department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetForDepartment", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetForDepartmentResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetForDepartmentAsync(string department);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/FindProfiles", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/FindProfilesResponse")]
        VigoBAS_Start.IDMServices.Profiles.GetUserResponse FindProfiles(VigoBAS_Start.IDMServices.Profiles.GetUserRequest userRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/FindProfiles", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/FindProfilesResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.GetUserResponse> FindProfilesAsync(VigoBAS_Start.IDMServices.Profiles.GetUserRequest userRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Update", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/UpdateResponse")]
        void Update(VigoBAS_Start.IDMServices.Profiles.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Update", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(VigoBAS_Start.IDMServices.Profiles.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Create", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/CreateResponse")]
        System.Guid Create(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Create", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/CreateResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateAsync(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Delete", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/DeleteResponse")]
        void Delete(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/Delete", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetFromGuid", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetFromGuidResponse")]
        VigoBAS_Start.IDMServices.Profiles.Profile GetFromGuid(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetFromGuid", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetFromGuidResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile> GetFromGuidAsync(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetProfilePicture", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetProfilePictureResponse")]
        VigoBAS_Start.IDMServices.Profiles.ProfilePicture GetProfilePicture(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetProfilePicture", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetProfilePictureResponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.ProfilePicture> GetProfilePictureAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/SetProfilePicture", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/SetProfilePictureResponse")]
        void SetProfilePicture(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/SetProfilePicture", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/SetProfilePictureResponse")]
        System.Threading.Tasks.Task SetProfilePictureAsync(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/ModifyProfilePictureFlags", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/ModifyProfilePictureFlagsR" +
            "esponse")]
        void ModifyProfilePictureFlags(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/ModifyProfilePictureFlags", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/ModifyProfilePictureFlagsR" +
            "esponse")]
        System.Threading.Tasks.Task ModifyProfilePictureFlagsAsync(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetUsersByHierarchyPath", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetUsersByHierarchyPathRes" +
            "ponse")]
        VigoBAS_Start.IDMServices.Profiles.Profile[] GetUsersByHierarchyPath(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetUsersByHierarchyPath", ReplyAction="http://basservices.vigobas.no/Users/Profiles/IProfiles/GetUsersByHierarchyPathRes" +
            "ponse")]
        System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetUsersByHierarchyPathAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfilesChannel : VigoBAS_Start.IDMServices.Profiles.IProfiles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfilesClient : System.ServiceModel.ClientBase<VigoBAS_Start.IDMServices.Profiles.IProfiles>, VigoBAS_Start.IDMServices.Profiles.IProfiles {
        
        public ProfilesClient() {
        }
        
        public ProfilesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfilesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfilesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfilesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VigoBAS_Start.IDMServices.Profiles.Profile Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        public VigoBAS_Start.IDMServices.Profiles.Profile[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public VigoBAS_Start.IDMServices.Profiles.Profile[] GetForDepartment(string department) {
            return base.Channel.GetForDepartment(department);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetForDepartmentAsync(string department) {
            return base.Channel.GetForDepartmentAsync(department);
        }
        
        public VigoBAS_Start.IDMServices.Profiles.GetUserResponse FindProfiles(VigoBAS_Start.IDMServices.Profiles.GetUserRequest userRequest) {
            return base.Channel.FindProfiles(userRequest);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.GetUserResponse> FindProfilesAsync(VigoBAS_Start.IDMServices.Profiles.GetUserRequest userRequest) {
            return base.Channel.FindProfilesAsync(userRequest);
        }
        
        public void Update(VigoBAS_Start.IDMServices.Profiles.Profile profile) {
            base.Channel.Update(profile);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(VigoBAS_Start.IDMServices.Profiles.Profile profile) {
            return base.Channel.UpdateAsync(profile);
        }
        
        public System.Guid Create(string firstName, string lastName) {
            return base.Channel.Create(firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateAsync(string firstName, string lastName) {
            return base.Channel.CreateAsync(firstName, lastName);
        }
        
        public void Delete(string username) {
            base.Channel.Delete(username);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string username) {
            return base.Channel.DeleteAsync(username);
        }
        
        public VigoBAS_Start.IDMServices.Profiles.Profile GetFromGuid(System.Guid userId) {
            return base.Channel.GetFromGuid(userId);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile> GetFromGuidAsync(System.Guid userId) {
            return base.Channel.GetFromGuidAsync(userId);
        }
        
        public VigoBAS_Start.IDMServices.Profiles.ProfilePicture GetProfilePicture(string username) {
            return base.Channel.GetProfilePicture(username);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.ProfilePicture> GetProfilePictureAsync(string username) {
            return base.Channel.GetProfilePictureAsync(username);
        }
        
        public void SetProfilePicture(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture) {
            base.Channel.SetProfilePicture(profilePicture);
        }
        
        public System.Threading.Tasks.Task SetProfilePictureAsync(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture) {
            return base.Channel.SetProfilePictureAsync(profilePicture);
        }
        
        public void ModifyProfilePictureFlags(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture) {
            base.Channel.ModifyProfilePictureFlags(profilePicture);
        }
        
        public System.Threading.Tasks.Task ModifyProfilePictureFlagsAsync(VigoBAS_Start.IDMServices.Profiles.ProfilePicture profilePicture) {
            return base.Channel.ModifyProfilePictureFlagsAsync(profilePicture);
        }
        
        public VigoBAS_Start.IDMServices.Profiles.Profile[] GetUsersByHierarchyPath(string path) {
            return base.Channel.GetUsersByHierarchyPath(path);
        }
        
        public System.Threading.Tasks.Task<VigoBAS_Start.IDMServices.Profiles.Profile[]> GetUsersByHierarchyPathAsync(string path) {
            return base.Channel.GetUsersByHierarchyPathAsync(path);
        }
    }
}
